config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  devise_scope :user do
    get 'users/mypage', to:'users/registrations#mypage', :as => :mypage_user_registration
  end
  
  get 'home/index'
  
  get 'item/all'  => 'item#all'
  
  get 'item/show/:item_id' => 'item#show'

  get 'item/brand'

  get 'item/fashion'

  get 'item/cosmetic'

  get 'item/shoes'

  get 'item/ect'
  
  get 'item/new' => 'item#new'
  
  get '/item/hashtag/:name', to:'item#hashtags'
  
  get 'item/search' 
  
  post 'item/create' => 'item#create'
  
  post 'item/:item_id/like' => "likes#like_toggle" , :as => 'item_like'
  
  root 'home#index'
  

end

app/models/item.rb
class Item < ActiveRecord::Base
resourcify
include Authority::UserAbilities
mount_uploader :image, AvatarUploader
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_and_belongs_to_many :tags

  after_create do
      item = Item.find_by(id: self.id)
      hashtags = self.content.scan(/#\w+/)
      hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        item.tags << tag
      end
  
  end
  
  before_update do
    item = Item.find_by(id: self.id)
    item.tags.clear #delete all and add again
    hashtags = self.content.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      item.tags << tag
    end
  end
  
  def self.search(search)
    
    if search
      find(:all, :conditions => ['content LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end  

end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  
  before_filter :must_be_admin, only: [:edit, :new, :create]
  
  def all
    @items= Item.all.order(created_at: :desc)
  end
  
  def show
    @item = Item.find(params[:item_id])
  end
  
  def brand
  end

  def fashion
    @item = Item.where("category": "fashion")
  end

  def cosmetic
    @item = Item.where("category": "cosmetic")
  end

  def shoes
    @item = Item.where("category": "shoes")
  end

  def ect
    @item = Item.where("category": "ect")
  end
  
  def new
    @item= Item.new
  end
  
  def edit

  end
  
  def destory

  end
  
  def create
    @item= Item.new
    @item.name= params[:name]
    @item.price= params[:price]
    @item.brand= params[:brand]
    @item.category= params[:category]
    @item.dueDate= params[:duedate]
    @item.url= params[:url]
    @item.content= params[:content]
    @item.image= params[:image]
    @item.save
    # authorize_action_for @item
    
    redirect_to '/item/all'
  end
  
  def hashtags
    tag =Tag.find_by(name: params[:name])
    @items= tag.items
  end
  
  def search
    @items = Item.search(params[:search])
  end
  
  def must_be_admin
    unless current_user && current_user.roles.last.name == 'admin'
      redirect_to root_path, notice: "Some message"
    end
  end
end

app/helpers/item_helper.rb
module ItemHelper
  def render_with_hashtags(content)
    content.gsub(/#\w+/){|word| link_to word, "/item/hashtag/#{word.downcase.delete('#')}"}.html_safe
  end
end

app/views/item/all.html.erb
<div class="well" style="padding-top:50px">
  <% @items.each do |item| %>
    <a href="/item/show/<%= item.id %>" style="font-color:black">
    <div class="item">
      <%= item.name %><br>
      <%= image_tag item.image.thumb.url %><br>
      <!--좋아요버튼-->
      <%= link_to item_like_path(item), class: "like-btn", method: :post, remote: :true do %>
      <div>
        <span><p><i class="fa fa-thumbs-up fa-x"></i></p></span>
      </div>
      <% end %> 
      <%= item.likes.size %><br> 
      <script>
        <% if current_user.is_like?(item) %>
          $('.like-btn').addClass('liked');
        <% else %>
          $('.like-btn').addClass('like-btn');
        <% end %>
      </script>

      가격: <%= item.price %><br>
      브랜드명: <%= item.brand %><br>
      카테고리: <%= item.category %><br>
      판매일: <%= item.dueDate %><br>
      주소: <%= item.url %><br>
      제품설명: <%= render_with_hashtags(item.content) %><br>
    </div>
    </a>
  <% end %>
</div>

<style>
    @import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
    .item{
        position :relative;
        padding-left :40px;
        width :45%;
        float: left;
        box-sizing :border-box;
        display :inline-block;
        margin-top :50px;
        /*margin-right: 55px;*/
        margin-left: 40px;
        box-shadow :0 2px 2px 0 rgba(0,0,0,0.16), 0 0 0 1px rgba(0,0,0, 0.08);
        font-family: 'Jeju Gothic', sans-serif;
    }
</style>

app/views/item/brand.html.erb
<h1>Item#brand</h1>
<p>Find me in app/views/item/brand.html.erb</p>

app/views/item/cosmetic.html.erb
<div class="container" style="padding-top:60px">
    <% @item.each do |item| %>
     
      <div class="item" >
            <%= item.name %><br>
            <%= image_tag item.image.thumb.url %><br>
            가격: <%= item.price %><br>
            브랜드명: <%= item.brand %><br>
            카테고리: <%= item.category %><br>
            판매일: <%= item.dueDate %><br>
            주소: <%= item.url %><br>
            제품설명: <%= item.content %>
      </div>
      <% end %>
      
</div>
<style>
    @import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
    .item{
        position :relative;
        padding-left :40px;
        width :45%;
        float: left;
        box-sizing :border-box;
        display :inline-block;
        margin-top :50px;
        /*margin-right: 55px;*/
        margin-left: 40px;
        box-shadow :0 2px 2px 0 rgba(0,0,0,0.16), 0 0 0 1px rgba(0,0,0, 0.08);
        font-family: 'Jeju Gothic', sans-serif;
    }
</style>

app/views/item/ect.html.erb
<div class="container" style="padding-top:60px">
    <% @item.each do |item| %>
     
      <div class="item" >
            <%= item.name %><br>
            <%= image_tag item.image.thumb.url %><br>
            가격: <%= item.price %><br>
            브랜드명: <%= item.brand %><br>
            카테고리: <%= item.category %><br>
            판매일: <%= item.dueDate %><br>
            주소: <%= item.url %><br>
            제품설명: <%= item.content %>
      </div>
      <% end %>
      
</div>
<style>
    @import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
    .item{
        position :relative;
        padding-left :40px;
        width :45%;
        float: left;
        box-sizing :border-box;
        display :inline-block;
        margin-top :50px;
        /*margin-right: 55px;*/
        margin-left: 40px;
        box-shadow :0 2px 2px 0 rgba(0,0,0,0.16), 0 0 0 1px rgba(0,0,0, 0.08);
        font-family: 'Jeju Gothic', sans-serif;
    }
</style>

app/views/item/fashion.html.erb
<div class="container" style="padding-top:60px">
    <% @item.each do |item| %>
     
      <div class="item" >
            <%= item.name %><br>
            <%= image_tag item.image.thumb.url %><br>
            가격: <%= item.price %><br>
            브랜드명: <%= item.brand %><br>
            카테고리: <%= item.category %><br>
            판매일: <%= item.dueDate %><br>
            주소: <%= item.url %><br>
            제품설명: <%= item.content %>
      </div>
      <% end %>
      
</div>
<style>
    @import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
    .item{
        position :relative;
        padding-left :40px;
        width :45%;
        float: left;
        box-sizing :border-box;
        display :inline-block;
        margin-top :50px;
        /*margin-right: 55px;*/
        margin-left: 40px;
        box-shadow :0 2px 2px 0 rgba(0,0,0,0.16), 0 0 0 1px rgba(0,0,0, 0.08);
        font-family: 'Jeju Gothic', sans-serif;
    }
</style>

app/views/item/hashtags.html.erb
<div class="well" style="padding-top:50px">
    <% @items.each do |item| %>
      <div class="item">
            <%= item.name %><br>
            <%= image_tag item.image.thumb.url %><br>
            가격: <%= item.price %><br>
            브랜드명: <%= item.brand %><br>
            카테고리: <%= item.category %><br>
            판매일: <%= item.dueDate %><br>
            주소: <%= item.url %><br>
            제품설명: <%= render_with_hashtags(item.content) %><br>
      </div>
    <% end %>
</div>
<style>
    .well{
        background-color :black;
    }
    .item{
        position :relative;
        padding-left :15px;
        width :50%;
        float: left;
        box-sizing: border-box;
    }
</style>

app/views/item/new.html.erb
<div class="container" style="padding-top:100px">
    <form action="/item/create" method="post" enctype="multipart/form-data">
      <div class="form-group">
        <label for="exampleInputPassword1">제품이름</label>
        <input class="form-control"placeholder="제품이름을 입력해주세요." name="name">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">가격</label>
        <input class="form-control" placeholder="가격을 입력해주세요." name="price">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">브랜드</label>
        <input class="form-control" placeholder="브랜드를 입력해주세요." name="brand">
      </div>
      
      <!--만기일 duedate로 설정하는 gem하고나서 수정하기-->
      <div class="form-group">
        <label for="exampleInputPassword1">만기일</label>
        <input class="form-control" type="integer" placeholder="만기일을 입력해주세요." name="duedate">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">URL</label></label>
        <input class="form-control" placeholder="URL을 입력해주세요." name="url">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">설명</label>
        <input class="form-control" placeholder="제품설명" name="content">
      </div>
      <label for="exampleInputPassword1">카테고리분류</label>
      <select name="category">
        <option value="cosmetic">cosmetic</option>
        <option value="fashion">fashion</option>
        <option value="shoes">shoes</option>
        <option value="etc">etc</option>
      </select><hr>
      <div class="form-group">
      <label for="exampleInputFile">제품 사진</label>
      <input type="file" id="exampleInputFile" name="image">
      <p class="help-block">제품사진을 올려주세요.</p>
      </div>
    
      <button type="submit" class="btn btn-default">Submit</button><br><br><br>
    </form>
</div>

app/views/item/search.html.erb
<% if @item.present? %>
  <%= render @item %>
<% else %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/item/shoes.html.erb
<div class="container" style="padding-top:60px">
    <% @item.each do |item| %>
     
      <div class="item" >
            <%= item.name %><br>
            <%= image_tag item.image.thumb.url %><br>
            가격: <%= item.price %><br>
            브랜드명: <%= item.brand %><br>
            카테고리: <%= item.category %><br>
            판매일: <%= item.dueDate %><br>
            주소: <%= item.url %><br>
            제품설명: <%= item.content %>
      </div>
      <% end %>
      
</div>
<style>
    @import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
    .item{
        position :relative;
        padding-left :40px;
        width :45%;
        float: left;
        box-sizing :border-box;
        display :inline-block;
        margin-top :50px;
        /*margin-right: 55px;*/
        margin-left: 40px;
        box-shadow :0 2px 2px 0 rgba(0,0,0,0.16), 0 0 0 1px rgba(0,0,0, 0.08);
        font-family: 'Jeju Gothic', sans-serif;
    }
</style>

app/views/item/show.html.erb
<div class="container" style="padding-top:60px">
    
     
      <div class="item" style="text-align:center">
            <%= @item.name %><br>
            <%= image_tag @item.image.thumb.url %><br>
            가격: <%= @item.price %><br>
            브랜드명: <%= @item.brand %><br>
            카테고리: <%= @item.category %><br>
            판매일: <%= @item.dueDate %><br>
            주소: <%= @item.url %><br>
            제품설명: <%= render_with_hashtags(@item.content) %><br>
      </div>
      
      
</div>
<style>
    @import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
    .item{
        position :relative;
        padding-left :40px;
        width :90%;
        float: left;
        box-sizing :border-box;
        display :inline-block;
        margin-top :50px;
        /*margin-right: 55px;*/
        /*margin-left: 40px;*/
        box-shadow :0 2px 2px 0 rgba(0,0,0,0.16), 0 0 0 1px rgba(0,0,0, 0.08);
        font-family: 'Jeju Gothic', sans-serif;
    }
</style>