config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  devise_scope :user do
    get 'users/mypage', to:'users/registrations#mypage', :as => :mypage_user_registration
  end
  
  get 'home/index'
  
  get 'item/all'  => 'item#all'
  
  get 'item/show/:item_id' => 'item#show'

  get 'item/brand'

  get 'item/fashion'

  get 'item/cosmetic'

  get 'item/shoes'

  get 'item/ect'
  
  get 'item/new' => 'item#new'
  
  get '/item/hashtag/:name', to:'item#hashtags'
  
  get 'item/search' 
  
  post 'item/create' => 'item#create'
  
  post 'item/:item_id/like' => "likes#like_toggle" , :as => 'item_like'
  
  root 'home#index'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onlimited::한정판_위에서다</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Bowlby+One+SC" rel="stylesheet">
  <!--핸드폰크기에맞춰서 글씨크기맞춰줌-->
  <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width"/>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>
<body>
<!-- Sidebar -->
<div id="wrapper">
  <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand"></li>
          <!-- Search -->
    			<div class="search-button">
    				<%= form_tag(item_all_path, :method => "get", :id => "search" ) do %>
    					<p>
    					<%= text_field_tag :search, params[:search], placeholder: "Search Items" %>
    					<%= submit_tag "Search"%>
    					</p>
    				<% end %>
    			</div>    
          <% if user_signed_in? %>
            <p style="color:white"><%= current_user.email %>님 환영합니다.</p>
            <p style="color:white"><%= current_user.name %>님 환영합니다.</p>
					  <li><%= link_to "My Profile", edit_user_registration_path %></li>
					  <li><%= link_to "My Page", mypage_user_registration_path %></li>
		        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
				  <% else %>
				    <li><%= link_to "Sign in", new_user_session_path %></li>
				    <li><%= link_to "Sign up", new_user_registration_path %></li>
				  <% end %><br>
          <li>
            <a href="/item/all">All</a>
          </li>
          <li>
            <a href="/item/fashion">Fashion</a>
          </li>
          <li>
            <a href="/item/cosmetic">Cosmetic</a>
          </li>
          <li>
            <a href="/item/shoes">Shoes</a>
          </li>
          <li>
            <a href="/item/brand">Brand</a>
          </li>
          <li>
            <a href="/item/etc">Etc</a>
          </li>
       </ul>
  </div>
</div>
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
      <a href="#menu-toggle" id="menu-toggle" style="color:white;"><span class="hamburger" style="height: 19px;margin-top: 4px;"></span></a>
      <!--mobile화면에서 home과 logim메뉴버튼-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/home/index">Home
            <span class="sr-only">(current)</span>
          </a>
        <% if  user_signed_in? %>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
<%= yield %>

</body>
</html>